// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IUrlShortnerService is an autogenerated mock type for the IUrlShortnerService type
type IUrlShortnerService struct {
	mock.Mock
}

// Metrics provides a mock function with given fields: w, r
func (_m *IUrlShortnerService) Metrics(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Redirect provides a mock function with given fields: w, r
func (_m *IUrlShortnerService) Redirect(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ShortenURL provides a mock function with given fields: w, r
func (_m *IUrlShortnerService) ShortenURL(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewIUrlShortnerService creates a new instance of IUrlShortnerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUrlShortnerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUrlShortnerService {
	mock := &IUrlShortnerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
